update uninstall

diff --git a/gitops/openshift-pipelines/lab-mce/task_mce_rolling_upgrade_acm.yaml b/gitops/openshift-pipelines/lab-mce/task_mce_rolling_upgrade_acm.yaml
--- a/gitops/openshift-pipelines/lab-mce/task_mce_rolling_upgrade_acm.yaml
+++ b/gitops/openshift-pipelines/lab-mce/task_mce_rolling_upgrade_acm.yaml
@@ -39,6 +39,10 @@ spec:
       KUSTOM=./gitops/kustomization/rhacm-operator/base-downstream-release-2.7-acm-d/kustomization.yaml
       S=$(params.upgrade-snapshot)
       echo "Updating upgrade-snapshot: $S"
+      if [ -z $S ]; then
+        echo "upgrade-snapshot cannot be undefined."
+        exit 1
+      fi
       cat $KUSTOM | sed -r "s/    newTag: 2.7.0-DOWNSTREAM-2022-10-25-02-23-54/    newTag: $S/g" > temp.yaml
       mv temp.yaml $KUSTOM
 
@@ -54,7 +58,7 @@ spec:
         namespace: open-cluster-management
       spec:
         displayName: Advanced Cluster Management
-        image: quay.io:443/acm-d/acm-custom-registry:$(params.upgrade-snapshot)
+        image: quay.io:443/acm-d/acm-custom-registry:$S
         publisher: Red Hat
         secrets:
         - multiclusterhub-operator-pull-secret
@@ -72,7 +76,7 @@ spec:
         namespace: multicluster-engine
       spec:
         displayName: MultiCluster Engine
-        image: quay.io:443/acm-d/mce-custom-registry:$(params.upgrade-snapshot)
+        image: quay.io:443/acm-d/mce-custom-registry:$S
         publisher: Red Hat
         sourceType: grpc
         updateStrategy:
