external-dns

diff --git a/gitops/openshift-pipelines/lab-mce/task_mce_check_status.yaml b/gitops/openshift-pipelines/lab-mce/task_mce_check_status.yaml
--- a/gitops/openshift-pipelines/lab-mce/task_mce_check_status.yaml
+++ b/gitops/openshift-pipelines/lab-mce/task_mce_check_status.yaml
@@ -43,13 +43,39 @@ spec:
 
       rc=$(oc get mch multiclusterhub -n $NS -ojsonpath='{.status.phase}')
       rc11=$(oc get csv $acm_current_csv -n $NS -ojsonpath='{.status.phase}')
+      rc21=$(oc get mce multiclusterengine -n $NS -ojsonpath='{.status.phase}')
+      rc22=$(oc get csv $mce_current_csv -n $NS2 -ojsonpath='{.status.phase}')
 
       echo "current mch operator phase                            : $(check $rc)"
       echo "current acm subscription currentCSV version           : $acm_current_csv"
       echo "current acm csv phase                                 : $(check $rc11)"
 
+
+      echo "current mce operator phase                            : $(check $rc21)"
+      echo "current mce subscription currentCSV version           : $mce_current_csv"
+      echo "current mce csv phase                                 : $(check $rc22)" 
+
+      _ATTEMPTS=0
+      until oc get sub mch multiclusterhub -n $NS -o jsonpath='{.status.phase}' | grep -q "Running";
+      do 
+          echo "Waiting 60s for MCH..."
+          _ATTEMPTS=$((_ATTEMPTS + 1))
+          sleep 60;
+          if [[ $_ATTEMPTS == 5 ]]; then
+              echo "Failed to start MCH in allotted time"
+              exit 1
+          fi
+      done
+
+      rc=$(oc get mch multiclusterhub -n $NS -ojsonpath='{.status.phase}')
+      rc11=$(oc get csv $acm_current_csv -n $NS -ojsonpath='{.status.phase}')
       rc21=$(oc get mce multiclusterengine -n $NS -ojsonpath='{.status.phase}')
       rc22=$(oc get csv $mce_current_csv -n $NS2 -ojsonpath='{.status.phase}')
+
+      echo "current mch operator phase                            : $(check $rc)"
+      echo "current acm subscription currentCSV version           : $acm_current_csv"
+      echo "current acm csv phase                                 : $(check $rc11)"
+
 
       echo "current mce operator phase                            : $(check $rc21)"
       echo "current mce subscription currentCSV version           : $mce_current_csv"
